#include <uuki/base/macros.h>

#include <rexo.h>

RX_TEST_CASE(macros, ilog2)
{
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(0), 0);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(1), 0);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(2), 1);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(3), 1);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(4), 2);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(17), 4);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(325), 8);
    RX_UINT_REQUIRE_EQUAL(W_ILOG2(18114), 14);
}

RX_TEST_CASE(macros, is_pow2)
{
    RX_BOOL_REQUIRE_TRUE(W_IS_POW2(1));
    RX_BOOL_REQUIRE_TRUE(W_IS_POW2(2));
    RX_BOOL_REQUIRE_TRUE(W_IS_POW2(4));
    RX_BOOL_REQUIRE_TRUE(W_IS_POW2(128));

    RX_BOOL_REQUIRE_FALSE(W_IS_POW2(0));
    RX_BOOL_REQUIRE_FALSE(W_IS_POW2(3));
    RX_BOOL_REQUIRE_FALSE(W_IS_POW2(82));
    RX_BOOL_REQUIRE_FALSE(W_IS_POW2(96));
}

RX_TEST_CASE(macros, round_down_pow2)
{
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(0ULL),
        0
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(1ULL),
        1
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(2ULL),
        2
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(3ULL),
        2
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(4ULL),
        4
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(932ULL),
        512
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_DOWN_POW2(2031ULL),
        1024
    );
}

RX_TEST_CASE(macros, round_up_pow2)
{
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(0ULL),
        0
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(1ULL),
        1
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(2ULL),
        2
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(3ULL),
        4
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(4ULL),
        4
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(61029ULL),
        65536
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(1221700ULL),
        2097152
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(137438953472ULL),
        137438953472
    );
    RX_UINT_REQUIRE_EQUAL(
        W_ROUND_UP_POW2(2100107785318157799ULL),
        2305843009213693952
    );
}

RX_TEST_CASE(macros, uint_is_add_wrapping)
{
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_ADD_WRAPPING(123, 123, 0));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_ADD_WRAPPING(123, 122, 1));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_ADD_WRAPPING(123, 121, 1, 1));

    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_ADD_WRAPPING(123, 123, 1));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_ADD_WRAPPING(123, 122, 2));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_ADD_WRAPPING(123, 121, 2, 1));
}

RX_TEST_CASE(macros, uint_is_sub_wrapping)
{
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_SUB_WRAPPING(123, 0, 0));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_SUB_WRAPPING(123, 1, 1));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_SUB_WRAPPING(123, 123, 123));

    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_SUB_WRAPPING(123, 123, 123, 1));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_SUB_WRAPPING(123, 0, 1));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_SUB_WRAPPING(123, 1, 1, 1));
}

RX_TEST_CASE(macros, uint_is_mul_wrapping)
{
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_MUL_WRAPPING(123, 5, 10));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_MUL_WRAPPING(123, 123, 0));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_MUL_WRAPPING(123, 123, 1));
    RX_BOOL_REQUIRE_FALSE(W_UINT_IS_MUL_WRAPPING(123, 10, 3, 4));

    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_MUL_WRAPPING(123, 66, 2));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_MUL_WRAPPING(123, 123, 2));
    RX_BOOL_REQUIRE_TRUE(W_UINT_IS_MUL_WRAPPING(123, 10, 13));
}

RX_TEST_CASE(macros, are_regions_overlapping)
{
    RX_BOOL_REQUIRE_FALSE(W_ARE_REGIONS_OVERLAPPING(0, 5, 10, 123));
    RX_BOOL_REQUIRE_FALSE(W_ARE_REGIONS_OVERLAPPING(10, 123, 0, 5));
    RX_BOOL_REQUIRE_FALSE(W_ARE_REGIONS_OVERLAPPING(0, 10, 10, 123));

    RX_BOOL_REQUIRE_TRUE(W_ARE_REGIONS_OVERLAPPING(0, 11, 10, 123));
    RX_BOOL_REQUIRE_TRUE(W_ARE_REGIONS_OVERLAPPING(10, 123, 0, 11));
}

int
main(
    int argc,
    const char **argv
)
{
    return rx_main(0, NULL, argc, argv) == RX_SUCCESS ? 0 : 1;
}
